#!/bin/bash
# BMAD QA Project Cleanup Script
# Generated by Quinn (Test Architect)

echo "🧹 BMAD QA Redundancy Cleanup - Phase 1 (Safe Deletions)"
echo "==============================================================="

# Phase 1: Remove obvious legacy/duplicate directories (LOW RISK)
echo "📁 Removing legacy archive directories..."

# Archive directory (1.9MB) - Complete legacy implementations
if [ -d "archive/" ]; then
    echo "  Removing archive/ (Legacy implementations superseded by current src/)"
    du -sh archive/
    rm -rf archive/
    echo "  ✅ archive/ removed"
fi

# Backups directory (232KB) - Exact duplicates and outdated demos  
if [ -d "backups/" ]; then
    echo "  Removing backups/ (Duplicate demo files)"
    du -sh backups/
    rm -rf backups/
    echo "  ✅ backups/ removed"
fi

# Phase 2: Remove specific backup files (LOW RISK)
echo "📄 Removing .backup files..."
find . -name "*.backup" -type f -exec echo "  Removing: {}" \; -exec rm {} \;

echo "🎯 Phase 1 cleanup completed!"
echo "==============================================================="

# Show remaining project size
echo "📊 Current project size:"
du -sh . --exclude=node_modules --exclude=.git

echo ""
echo "✅ Safe cleanup completed. Run 'git status' to review changes."