version: '1.0.0'
log_level: 'INFO'
log_file: math_solver.log
use_gpu: false
use_mps: true
num_threads: 8

nlp:
  model_path: 'models/nlp'
  language: 'zh'
  max_length: 512
  device_settings:
    use_mps: true
    use_gpu: false
    fallback_to_cpu: true
    device_priority: ['mps', 'cpu']

solver:
  max_iterations: 1000
  tolerance: 0.000001
  device: 'mps'

output:
  save_steps: true
  save_path: 'results'
  format: 'json'
